Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Console\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Console-Kernel.html"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Aschedule\u0028\u0029",
            "name": "schedule",
            "summary": "Define\u0020the\u0020application\u0027s\u0020command\u0020schedule.",
            "url": "classes/App-Console-Kernel.html#method_schedule"
        },                {
            "fqsen": "\\App\\Console\\Kernel\u003A\u003Acommands\u0028\u0029",
            "name": "commands",
            "summary": "Register\u0020the\u0020commands\u0020for\u0020the\u0020application.",
            "url": "classes/App-Console-Kernel.html#method_commands"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler",
            "name": "Handler",
            "summary": "",
            "url": "classes/App-Exceptions-Handler.html"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020the\u0020exception\u0020handling\u0020callbacks\u0020for\u0020the\u0020application.",
            "url": "classes/App-Exceptions-Handler.html#method_register"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024dontReport",
            "name": "dontReport",
            "summary": "A\u0020list\u0020of\u0020the\u0020exception\u0020types\u0020that\u0020are\u0020not\u0020reported.",
            "url": "classes/App-Exceptions-Handler.html#property_dontReport"
        },                {
            "fqsen": "\\App\\Exceptions\\Handler\u003A\u003A\u0024dontFlash",
            "name": "dontFlash",
            "summary": "A\u0020list\u0020of\u0020the\u0020inputs\u0020that\u0020are\u0020never\u0020flashed\u0020for\u0020validation\u0020exceptions.",
            "url": "classes/App-Exceptions-Handler.html#property_dontFlash"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controlador",
            "name": "Controlador",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controlador.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controlador\u003A\u003Ainicio\u0028\u0029",
            "name": "inicio",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controlador.html#method_inicio"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerAdmin",
            "name": "ControllerAdmin",
            "summary": "",
            "url": "classes/App-Http-Controllers-ControllerAdmin.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerAdmin\u003A\u003AlistarUsuarios\u0028\u0029",
            "name": "listarUsuarios",
            "summary": "Lista\u0020de\u0020usuarios\u0020con\u0020sus\u0020propiedades",
            "url": "classes/App-Http-Controllers-ControllerAdmin.html#method_listarUsuarios"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerAdmin\u003A\u003AaltaUsuario\u0028\u0029",
            "name": "altaUsuario",
            "summary": "Funci\u00F3n\u0020que\u0020regisrea\u0020un\u0020usuario\u0020en\u0020la\u0020base\u0020de\u0020datos\nseg\u00FAn\u0020la\u0020informaci\u00F3n\u0020pasada\u0020a\u0020trav\u00E9s\u0020de\u0020la\u0020petici\u00F3n",
            "url": "classes/App-Http-Controllers-ControllerAdmin.html#method_altaUsuario"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerAdmin\u003A\u003AborrarUsuario\u0028\u0029",
            "name": "borrarUsuario",
            "summary": "Borra\u0020un\u0020usuario\u0020de\u0020la\u0020BBDD",
            "url": "classes/App-Http-Controllers-ControllerAdmin.html#method_borrarUsuario"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerAdmin\u003A\u003AtogleActivado\u0028\u0029",
            "name": "togleActivado",
            "summary": "Activa\u0020o\u0020desactiva\u0020al\u0020usuario\u0020enviado\u0020por\u0020la\u0020petici\u00F3n",
            "url": "classes/App-Http-Controllers-ControllerAdmin.html#method_togleActivado"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerGeneric",
            "name": "ControllerGeneric",
            "summary": "",
            "url": "classes/App-Http-Controllers-ControllerGeneric.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerGeneric\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Funci\u00F3n\u0020que\u0020comprueba\u0020la\u0020existencia\u0020de\u0020un\u0020usuario\u0020seg\u00FAn\u0020el\u0020correo\u0020y\u0020la\u0020contrase\u00F1a\nasignada\u0020por\u0020par\u00E1metros\u0020en\u0020la\u0020petici\u00F3n",
            "url": "classes/App-Http-Controllers-ControllerGeneric.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerGeneric\u003A\u003AobtenerCiudadesFormulario\u0028\u0029",
            "name": "obtenerCiudadesFormulario",
            "summary": "Obtiene\u0020las\u0020ciudades\u0020para\u0020el\u0020select\u0020del\u0020formulario\u0020de\u0020registro",
            "url": "classes/App-Http-Controllers-ControllerGeneric.html#method_obtenerCiudadesFormulario"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerGeneric\u003A\u003AobtenerPreferenciasFormulario\u0028\u0029",
            "name": "obtenerPreferenciasFormulario",
            "summary": "Obtiene\u0020las\u0020preferencias\u0020para\u0020el\u0020select\u0020del\u0020formulario\u0020de\u0020registro",
            "url": "classes/App-Http-Controllers-ControllerGeneric.html#method_obtenerPreferenciasFormulario"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser",
            "name": "ControllerUser",
            "summary": "",
            "url": "classes/App-Http-Controllers-ControllerUser.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AlistarAfinidades\u0028\u0029",
            "name": "listarAfinidades",
            "summary": "Devuelve\u0020una\u0020lista\u0020de\u0020gente\u0020af\u00EDn\u0020al\u0020usuario\u0020introducido",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_listarAfinidades"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AgetAnio\u0028\u0029",
            "name": "getAnio",
            "summary": "Obtiene\u0020una\u0020fecha\u0020formateada\u0020seg\u00FAn\u0020la\u0020edad\u0020introducida\npara\u0020compararla\u0020con\u0020las\u0020edades\u0020m\u00EDnimas\u0020y\u0020m\u00E1ximas\u0020que\u0020el\u0020usuario\nindique\u0020en\u0020sus\u0020preferencias",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_getAnio"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AgenerarCompatibilidad\u0028\u0029",
            "name": "generarCompatibilidad",
            "summary": "Genera\u0020un\u0020porcentaje\u0020de\u0020compatibilidad\u0020para\u0020cada\u0020uno\u0020de\u0020los\u0020usuarios\u0020de\u0020la\u0020lista\u0020dada",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_generarCompatibilidad"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AcalcularPorcentajeCompatibilidad\u0028\u0029",
            "name": "calcularPorcentajeCompatibilidad",
            "summary": "Calcula\u0020un\u0020porcentaje\u0020entre\u0020dos\u0020valores",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_calcularPorcentajeCompatibilidad"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AperfilUsuario\u0028\u0029",
            "name": "perfilUsuario",
            "summary": "Devuelve\u0020la\u0020informaci\u00F3n\u0020del\u0020perfil\u0020del\u0020usuario",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_perfilUsuario"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003Alike\u0028\u0029",
            "name": "like",
            "summary": "Inserta\u0020un\u0020like\u0020entre\u0020dos\u0020usuarios",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_like"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AesMatch\u0028\u0029",
            "name": "esMatch",
            "summary": "Devuelve\u0020true\u0020si\u0020dos\u0020usuarios\u0020han\u0020obtenido\u0020un\u0020like\u0020mutuo",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_esMatch"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003Adislike\u0028\u0029",
            "name": "dislike",
            "summary": "Inserta\u0020un\u0020dislike\u0020entre\u0020dos\u0020usuarios",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_dislike"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AborrarPerfil\u0028\u0029",
            "name": "borrarPerfil",
            "summary": "Borra\u0020el\u0020perfil\u0020de\u0020un\u0020usuario\u0020en\u0020concreto",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_borrarPerfil"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AcerrarSesion\u0028\u0029",
            "name": "cerrarSesion",
            "summary": "Cierra\u0020la\u0020sesi\u00F3n\u0020de\u0020un\u0020usuario\u0020en\u0020concreto",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_cerrarSesion"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AlistarAmigos\u0028\u0029",
            "name": "listarAmigos",
            "summary": "Lista\u0020las\u0020personas\u0020con\u0020un\u0020like\u0020mutuo",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_listarAmigos"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AlistarGenteCerca\u0028\u0029",
            "name": "listarGenteCerca",
            "summary": "Lista\u0020las\u0020personas\u0020de\u0020la\u0020misma\u0020ciudad\u0020que\u0020el\u0020usuario",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_listarGenteCerca"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ControllerUser\u003A\u003AlistarLesGusto\u0028\u0029",
            "name": "listarLesGusto",
            "summary": "Lista\u0020las\u0020personas\u0020que\u0020han\u0020dado\u0020like\u0020al\u0020perfil\u0020del\u0020usuario",
            "url": "classes/App-Http-Controllers-ControllerUser.html#method_listarLesGusto"
        },                {
            "fqsen": "\\App\\Http\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "classes/App-Http-Kernel.html"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middleware",
            "name": "middleware",
            "summary": "The\u0020application\u0027s\u0020global\u0020HTTP\u0020middleware\u0020stack.",
            "url": "classes/App-Http-Kernel.html#property_middleware"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024middlewareGroups",
            "name": "middlewareGroups",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware\u0020groups.",
            "url": "classes/App-Http-Kernel.html#property_middlewareGroups"
        },                {
            "fqsen": "\\App\\Http\\Kernel\u003A\u003A\u0024routeMiddleware",
            "name": "routeMiddleware",
            "summary": "The\u0020application\u0027s\u0020route\u0020middleware.",
            "url": "classes/App-Http-Kernel.html#property_routeMiddleware"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate",
            "name": "Authenticate",
            "summary": "",
            "url": "classes/App-Http-Middleware-Authenticate.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\Authenticate\u003A\u003AredirectTo\u0028\u0029",
            "name": "redirectTo",
            "summary": "Get\u0020the\u0020path\u0020the\u0020user\u0020should\u0020be\u0020redirected\u0020to\u0020when\u0020they\u0020are\u0020not\u0020authenticated.",
            "url": "classes/App-Http-Middleware-Authenticate.html#method_redirectTo"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies",
            "name": "EncryptCookies",
            "summary": "",
            "url": "classes/App-Http-Middleware-EncryptCookies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\EncryptCookies\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020cookies\u0020that\u0020should\u0020not\u0020be\u0020encrypted.",
            "url": "classes/App-Http-Middleware-EncryptCookies.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\MidAdmin",
            "name": "MidAdmin",
            "summary": "",
            "url": "classes/App-Http-Middleware-MidAdmin.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\MidAdmin\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-MidAdmin.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\MidUser",
            "name": "MidUser",
            "summary": "",
            "url": "classes/App-Http-Middleware-MidUser.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\MidUser\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-MidUser.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "name": "PreventRequestsDuringMaintenance",
            "summary": "",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\PreventRequestsDuringMaintenance\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020reachable\u0020while\u0020maintenance\u0020mode\u0020is\u0020enabled.",
            "url": "classes/App-Http-Middleware-PreventRequestsDuringMaintenance.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated",
            "name": "RedirectIfAuthenticated",
            "summary": "",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\RedirectIfAuthenticated\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/App-Http-Middleware-RedirectIfAuthenticated.html#method_handle"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings",
            "name": "TrimStrings",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrimStrings.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrimStrings\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020names\u0020of\u0020the\u0020attributes\u0020that\u0020should\u0020not\u0020be\u0020trimmed.",
            "url": "classes/App-Http-Middleware-TrimStrings.html#property_except"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts",
            "name": "TrustHosts",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustHosts.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustHosts\u003A\u003Ahosts\u0028\u0029",
            "name": "hosts",
            "summary": "Get\u0020the\u0020host\u0020patterns\u0020that\u0020should\u0020be\u0020trusted.",
            "url": "classes/App-Http-Middleware-TrustHosts.html#method_hosts"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies",
            "name": "TrustProxies",
            "summary": "",
            "url": "classes/App-Http-Middleware-TrustProxies.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024proxies",
            "name": "proxies",
            "summary": "The\u0020trusted\u0020proxies\u0020for\u0020this\u0020application.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_proxies"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\TrustProxies\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "The\u0020headers\u0020that\u0020should\u0020be\u0020used\u0020to\u0020detect\u0020proxies.",
            "url": "classes/App-Http-Middleware-TrustProxies.html#property_headers"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken",
            "name": "VerifyCsrfToken",
            "summary": "",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware\\VerifyCsrfToken\u003A\u003A\u0024except",
            "name": "except",
            "summary": "The\u0020URIs\u0020that\u0020should\u0020be\u0020excluded\u0020from\u0020CSRF\u0020verification.",
            "url": "classes/App-Http-Middleware-VerifyCsrfToken.html#property_except"
        },                {
            "fqsen": "\\App\\Models\\Ciudad",
            "name": "Ciudad",
            "summary": "",
            "url": "classes/App-Models-Ciudad.html"
        },                {
            "fqsen": "\\App\\Models\\Ciudad\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Ciudad.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Compatibilidad",
            "name": "Compatibilidad",
            "summary": "",
            "url": "classes/App-Models-Compatibilidad.html"
        },                {
            "fqsen": "\\App\\Models\\Compatibilidad\u003A\u003AusuarioCompatible\u0028\u0029",
            "name": "usuarioCompatible",
            "summary": "",
            "url": "classes/App-Models-Compatibilidad.html#method_usuarioCompatible"
        },                {
            "fqsen": "\\App\\Models\\Compatibilidad\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Compatibilidad.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Compatibilidad\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Compatibilidad.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Dislike",
            "name": "Dislike",
            "summary": "",
            "url": "classes/App-Models-Dislike.html"
        },                {
            "fqsen": "\\App\\Models\\Dislike\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Dislike.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Genero",
            "name": "Genero",
            "summary": "",
            "url": "classes/App-Models-Genero.html"
        },                {
            "fqsen": "\\App\\Models\\Genero\u003A\u003Ausuarios\u0028\u0029",
            "name": "usuarios",
            "summary": "",
            "url": "classes/App-Models-Genero.html#method_usuarios"
        },                {
            "fqsen": "\\App\\Models\\GustosGenero",
            "name": "GustosGenero",
            "summary": "",
            "url": "classes/App-Models-GustosGenero.html"
        },                {
            "fqsen": "\\App\\Models\\GustosGenero\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-GustosGenero.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Like",
            "name": "Like",
            "summary": "",
            "url": "classes/App-Models-Like.html"
        },                {
            "fqsen": "\\App\\Models\\Like\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Like.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Pass",
            "name": "Pass",
            "summary": "",
            "url": "classes/App-Models-Pass.html"
        },                {
            "fqsen": "\\App\\Models\\Pass\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Pass.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Pass\u003A\u003A\u0024primaryKey",
            "name": "primaryKey",
            "summary": "",
            "url": "classes/App-Models-Pass.html#property_primaryKey"
        },                {
            "fqsen": "\\App\\Models\\Preferencia",
            "name": "Preferencia",
            "summary": "",
            "url": "classes/App-Models-Preferencia.html"
        },                {
            "fqsen": "\\App\\Models\\PrefUsuarios",
            "name": "PrefUsuarios",
            "summary": "",
            "url": "classes/App-Models-PrefUsuarios.html"
        },                {
            "fqsen": "\\App\\Models\\PrefUsuarios\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-PrefUsuarios.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024casts",
            "name": "casts",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#property_casts"
        },                {
            "fqsen": "\\App\\Models\\Usuario",
            "name": "Usuario",
            "summary": "",
            "url": "classes/App-Models-Usuario.html"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003Apass\u0028\u0029",
            "name": "pass",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_pass"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AgustosGenero\u0028\u0029",
            "name": "gustosGenero",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_gustosGenero"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003Apreferencias\u0028\u0029",
            "name": "preferencias",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_preferencias"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AlikesDados\u0028\u0029",
            "name": "likesDados",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_likesDados"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AlikesRecibidos\u0028\u0029",
            "name": "likesRecibidos",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_likesRecibidos"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AdislikesDados\u0028\u0029",
            "name": "dislikesDados",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_dislikesDados"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AdislikesRecibidos\u0028\u0029",
            "name": "dislikesRecibidos",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_dislikesRecibidos"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AcompatibilidadOrigen\u0028\u0029",
            "name": "compatibilidadOrigen",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_compatibilidadOrigen"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003AcompatibilidadDestino\u0028\u0029",
            "name": "compatibilidadDestino",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#method_compatibilidadDestino"
        },                {
            "fqsen": "\\App\\Models\\Usuario\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Usuario.html#property_fillable"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider",
            "name": "AuthServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AuthServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020authentication\u0020\/\u0020authorization\u0020services.",
            "url": "classes/App-Providers-AuthServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\AuthServiceProvider\u003A\u003A\u0024policies",
            "name": "policies",
            "summary": "The\u0020policy\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-AuthServiceProvider.html#property_policies"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider",
            "name": "BroadcastServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-BroadcastServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\BroadcastServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-BroadcastServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider",
            "name": "EventServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-EventServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020events\u0020for\u0020your\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\EventServiceProvider\u003A\u003A\u0024listen",
            "name": "listen",
            "summary": "The\u0020event\u0020listener\u0020mappings\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-EventServiceProvider.html#property_listen"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider",
            "name": "RouteServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-RouteServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Define\u0020your\u0020route\u0020model\u0020bindings,\u0020pattern\u0020filters,\u0020etc.",
            "url": "classes/App-Providers-RouteServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003AconfigureRateLimiting\u0028\u0029",
            "name": "configureRateLimiting",
            "summary": "Configure\u0020the\u0020rate\u0020limiters\u0020for\u0020the\u0020application.",
            "url": "classes/App-Providers-RouteServiceProvider.html#method_configureRateLimiting"
        },                {
            "fqsen": "\\App\\Providers\\RouteServiceProvider\u003A\u003AHOME",
            "name": "HOME",
            "summary": "The\u0020path\u0020to\u0020the\u0020\u0022home\u0022\u0020route\u0020for\u0020your\u0020application.",
            "url": "classes/App-Providers-RouteServiceProvider.html#constant_HOME"
        },                {
            "fqsen": "\\Database\\Factories\\CompatibilidadFactory",
            "name": "CompatibilidadFactory",
            "summary": "",
            "url": "classes/Database-Factories-CompatibilidadFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\CompatibilidadFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-CompatibilidadFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\DislikesFactory",
            "name": "DislikesFactory",
            "summary": "",
            "url": "classes/Database-Factories-DislikesFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\DislikesFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-DislikesFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\GustosGeneroFactory",
            "name": "GustosGeneroFactory",
            "summary": "",
            "url": "classes/Database-Factories-GustosGeneroFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\GustosGeneroFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-GustosGeneroFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\GustosGeneroFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "",
            "url": "classes/Database-Factories-GustosGeneroFactory.html#property_model"
        },                {
            "fqsen": "\\Database\\Factories\\GustosGeneroFactory\u003A\u003A\u0024idUsuario",
            "name": "idUsuario",
            "summary": "",
            "url": "classes/Database-Factories-GustosGeneroFactory.html#property_idUsuario"
        },                {
            "fqsen": "\\Database\\Factories\\GustosGeneroFactory\u003A\u003A\u0024idGenero",
            "name": "idGenero",
            "summary": "",
            "url": "classes/Database-Factories-GustosGeneroFactory.html#property_idGenero"
        },                {
            "fqsen": "\\Database\\Factories\\LikesFactory",
            "name": "LikesFactory",
            "summary": "",
            "url": "classes/Database-Factories-LikesFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\LikesFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-LikesFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\PassFactory",
            "name": "PassFactory",
            "summary": "",
            "url": "classes/Database-Factories-PassFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\PassFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-PassFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\PassFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "",
            "url": "classes/Database-Factories-PassFactory.html#property_model"
        },                {
            "fqsen": "\\Database\\Factories\\PassFactory\u003A\u003A\u0024idUsuario",
            "name": "idUsuario",
            "summary": "",
            "url": "classes/Database-Factories-PassFactory.html#property_idUsuario"
        },                {
            "fqsen": "\\Database\\Factories\\PrefUsuariosFactory",
            "name": "PrefUsuariosFactory",
            "summary": "",
            "url": "classes/Database-Factories-PrefUsuariosFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\PrefUsuariosFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-PrefUsuariosFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\PrefUsuariosFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "",
            "url": "classes/Database-Factories-PrefUsuariosFactory.html#property_model"
        },                {
            "fqsen": "\\Database\\Factories\\PrefUsuariosFactory\u003A\u003A\u0024idUsuario",
            "name": "idUsuario",
            "summary": "",
            "url": "classes/Database-Factories-PrefUsuariosFactory.html#property_idUsuario"
        },                {
            "fqsen": "\\Database\\Factories\\PrefUsuariosFactory\u003A\u003A\u0024idPreferencia",
            "name": "idPreferencia",
            "summary": "",
            "url": "classes/Database-Factories-PrefUsuariosFactory.html#property_idPreferencia"
        },                {
            "fqsen": "\\Database\\Factories\\PrefUsuariosFactory\u003A\u003A\u0024intensidad",
            "name": "intensidad",
            "summary": "",
            "url": "classes/Database-Factories-PrefUsuariosFactory.html#property_intensidad"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory",
            "name": "UserFactory",
            "summary": "",
            "url": "classes/Database-Factories-UserFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-UserFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Aunverified\u0028\u0029",
            "name": "unverified",
            "summary": "Indicate\u0020that\u0020the\u0020model\u0027s\u0020email\u0020address\u0020should\u0020be\u0020unverified.",
            "url": "classes/Database-Factories-UserFactory.html#method_unverified"
        },                {
            "fqsen": "\\Database\\Factories\\UsuarioFactory",
            "name": "UsuarioFactory",
            "summary": "",
            "url": "classes/Database-Factories-UsuarioFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UsuarioFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-UsuarioFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UsuarioFactory\u003A\u003A\u0024model",
            "name": "model",
            "summary": "",
            "url": "classes/Database-Factories-UsuarioFactory.html#property_model"
        },                {
            "fqsen": "\\Database\\Factories\\UsuarioFactory\u003A\u003A\u0024idUsuario",
            "name": "idUsuario",
            "summary": "",
            "url": "classes/Database-Factories-UsuarioFactory.html#property_idUsuario"
        },                {
            "fqsen": "\\CreateUsuarios",
            "name": "CreateUsuarios",
            "summary": "",
            "url": "classes/CreateUsuarios.html"
        },                {
            "fqsen": "\\CreateUsuarios\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateUsuarios.html#method_up"
        },                {
            "fqsen": "\\CreateUsuarios\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateUsuarios.html#method_down"
        },                {
            "fqsen": "\\CreateGeneros",
            "name": "CreateGeneros",
            "summary": "",
            "url": "classes/CreateGeneros.html"
        },                {
            "fqsen": "\\CreateGeneros\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateGeneros.html#method_up"
        },                {
            "fqsen": "\\CreateGeneros\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateGeneros.html#method_down"
        },                {
            "fqsen": "\\CreatePreferencias",
            "name": "CreatePreferencias",
            "summary": "",
            "url": "classes/CreatePreferencias.html"
        },                {
            "fqsen": "\\CreatePreferencias\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreatePreferencias.html#method_up"
        },                {
            "fqsen": "\\CreatePreferencias\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreatePreferencias.html#method_down"
        },                {
            "fqsen": "\\CreatePreferenciasUsuarios",
            "name": "CreatePreferenciasUsuarios",
            "summary": "",
            "url": "classes/CreatePreferenciasUsuarios.html"
        },                {
            "fqsen": "\\CreatePreferenciasUsuarios\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreatePreferenciasUsuarios.html#method_up"
        },                {
            "fqsen": "\\CreatePreferenciasUsuarios\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreatePreferenciasUsuarios.html#method_down"
        },                {
            "fqsen": "\\CreateLikes",
            "name": "CreateLikes",
            "summary": "",
            "url": "classes/CreateLikes.html"
        },                {
            "fqsen": "\\CreateLikes\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateLikes.html#method_up"
        },                {
            "fqsen": "\\CreateLikes\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateLikes.html#method_down"
        },                {
            "fqsen": "\\CreateDislikes",
            "name": "CreateDislikes",
            "summary": "",
            "url": "classes/CreateDislikes.html"
        },                {
            "fqsen": "\\CreateDislikes\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateDislikes.html#method_up"
        },                {
            "fqsen": "\\CreateDislikes\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateDislikes.html#method_down"
        },                {
            "fqsen": "\\CreateCompatibilidad",
            "name": "CreateCompatibilidad",
            "summary": "",
            "url": "classes/CreateCompatibilidad.html"
        },                {
            "fqsen": "\\CreateCompatibilidad\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateCompatibilidad.html#method_up"
        },                {
            "fqsen": "\\CreateCompatibilidad\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateCompatibilidad.html#method_down"
        },                {
            "fqsen": "\\CreateGustosGenero",
            "name": "CreateGustosGenero",
            "summary": "",
            "url": "classes/CreateGustosGenero.html"
        },                {
            "fqsen": "\\CreateGustosGenero\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreateGustosGenero.html#method_up"
        },                {
            "fqsen": "\\CreateGustosGenero\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreateGustosGenero.html#method_down"
        },                {
            "fqsen": "\\CreatePass",
            "name": "CreatePass",
            "summary": "",
            "url": "classes/CreatePass.html"
        },                {
            "fqsen": "\\CreatePass\u003A\u003Aup\u0028\u0029",
            "name": "up",
            "summary": "Run\u0020the\u0020migrations.",
            "url": "classes/CreatePass.html#method_up"
        },                {
            "fqsen": "\\CreatePass\u003A\u003Adown\u0028\u0029",
            "name": "down",
            "summary": "Reverse\u0020the\u0020migrations.",
            "url": "classes/CreatePass.html#method_down"
        },                {
            "fqsen": "\\Database\\Seeders\\CompatibilidadSeeder",
            "name": "CompatibilidadSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-CompatibilidadSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\CompatibilidadSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-CompatibilidadSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder",
            "name": "DatabaseSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DatabaseSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Seed\u0020the\u0020application\u0027s\u0020database.",
            "url": "classes/Database-Seeders-DatabaseSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\DislikesSeeder",
            "name": "DislikesSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DislikesSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DislikesSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-DislikesSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\GustosGenero",
            "name": "GustosGenero",
            "summary": "",
            "url": "classes/Database-Seeders-GustosGenero.html"
        },                {
            "fqsen": "\\Database\\Seeders\\GustosGenero\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-GustosGenero.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\LikesSeeder",
            "name": "LikesSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-LikesSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\LikesSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-LikesSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\PassSeeder",
            "name": "PassSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-PassSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\PassSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-PassSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\PrefUsuariosSeeder",
            "name": "PrefUsuariosSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-PrefUsuariosSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\PrefUsuariosSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-PrefUsuariosSeeder.html#method_run"
        },                {
            "fqsen": "\\Database\\Seeders\\UsuarioSeeder",
            "name": "UsuarioSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-UsuarioSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\UsuarioSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Run\u0020the\u0020database\u0020seeds.",
            "url": "classes/Database-Seeders-UsuarioSeeder.html#method_run"
        },                {
            "fqsen": "\\LARAVEL_START",
            "name": "LARAVEL_START",
            "summary": "",
            "url": "namespaces/default.html#constant_LARAVEL_START"
        },                {
            "fqsen": "\\Tests\\CreatesApplication",
            "name": "CreatesApplication",
            "summary": "",
            "url": "classes/Tests-CreatesApplication.html"
        },                {
            "fqsen": "\\Tests\\CreatesApplication\u003A\u003AcreateApplication\u0028\u0029",
            "name": "createApplication",
            "summary": "Creates\u0020the\u0020application.",
            "url": "classes/Tests-CreatesApplication.html#method_createApplication"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Feature-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest\u003A\u003Atest_example\u0028\u0029",
            "name": "test_example",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Feature-ExampleTest.html#method_test_example"
        },                {
            "fqsen": "\\Tests\\TestCase",
            "name": "TestCase",
            "summary": "",
            "url": "classes/Tests-TestCase.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Unit-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest\u003A\u003Atest_example\u0028\u0029",
            "name": "test_example",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Unit-ExampleTest.html#method_test_example"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/app-console.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/app-exceptions.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Http\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-http-middleware.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\Database\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/database-factories.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Database\\Seeders",
            "name": "Seeders",
            "summary": "",
            "url": "namespaces/database-seeders.html"
        },                {
            "fqsen": "\\Tests",
            "name": "Tests",
            "summary": "",
            "url": "namespaces/tests.html"
        },                {
            "fqsen": "\\Tests\\Feature",
            "name": "Feature",
            "summary": "",
            "url": "namespaces/tests-feature.html"
        },                {
            "fqsen": "\\Tests\\Unit",
            "name": "Unit",
            "summary": "",
            "url": "namespaces/tests-unit.html"
        }            ]
);
